/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ACDMPlatform } from "./ACDMPlatform";
export type { ACDMToken } from "./ACDMToken";
export type { XXXDAO } from "./XXXDAO";
export type { XXXStake } from "./XXXStake";
export type { XXXToken } from "./XXXToken";
