/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ACDMPlatform__factory } from "./ACDMPlatform__factory";
export { ACDMToken__factory } from "./ACDMToken__factory";
export { XXXDAO__factory } from "./XXXDAO__factory";
export { XXXStake__factory } from "./XXXStake__factory";
export { XXXToken__factory } from "./XXXToken__factory";
