/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IDAO, IDAOInterface } from "../../../contracts/interfaces/IDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
    ],
    name: "canUnstake",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "voter",
        type: "address",
      },
    ],
    name: "emptyDeposit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOInterface {
    return new utils.Interface(_abi) as IDAOInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDAO {
    return new Contract(address, _abi, signerOrProvider) as IDAO;
  }
}
